version: "3.9"

name: infrastructure

networks:
  public:
    external: true
    name: public

volumes:
  vault_data:
  kafka_data:

services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: unless-stopped
    networks:
      - public
    ports:
      - "809:80"
      - "8089:8080" # dashboard
    command:
      - --log.level=INFO
      - --api.dashboard=true
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      # Recomendado para evitar líos si hay más redes:
      - --providers.docker.network=public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  vault:
    image: hashicorp/vault:1.16
    container_name: vault
    restart: unless-stopped
    networks:
      - public
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      # DEV mode (para empezar). En prod, no uses -dev.
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_TOKEN:-root}
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    command: vault server -dev
    volumes:
      - vault_data:/vault/file

  consul:
    image: hashicorp/consul:1.17
    container_name: consul
    restart: unless-stopped
    networks:
      - public
    ports:
      - "8500:8500"
    command: agent -server -bootstrap-expect=1 -ui -client=0.0.0.0

  # ---------------------------
  # Kafka (KRaft mode, no Zookeeper)
  # Bootstrap interno para micros: kafka:9092
  # ---------------------------
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    restart: unless-stopped
    networks:
      - public
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      # KRaft single-node
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"

      # Listeners
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

      # Single-node sane defaults
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      # Required for KRaft formatting (any stable UUID-like string works)
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    networks:
      - public
    depends_on:
      - kafka
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    ports:
      - "8091:8080"   # host:container